### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by MohammadtaghiFarkhondekar** [MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD#36]
## This project need your helping 👍 
* Problems need fixing : 
- [ ]  CPU PKG Power using ( CPU PKG power using is more than Normal - In windows Just use 0.5W but in macOS use 2W in rest time).
- [x]  CPU frequency ( CPU frequency is more than Normal , In rest time CPU frequency is 1.58 Ghz . I know VoodooI2C use 0.6Ghz !! bc when it removed from loading CPU frequency is 1.08 or 1.0Ghz.)
- [ ] Making OpenCore bootloader .

**Comment by MohammadtaghiFarkhondekar** [comment]
@iSWORD @shivaluma @sergeycherepanov @valinor61 @ZiQiLN @FerVillanuevas @tuanngokien

**Comment by iSWORD** [comment]
does this help with the first two issues or is it too old? https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh#hardware

unfortunately i don't have any experience with OpenCore but the [docs](https://github.com/acidanthera/OpenCorePkg/raw/master/Docs/Configuration.pdf) and [guide](https://khronokernel.github.io/Opencore-Vanilla-Desktop-Guide/) look pretty neat and straightforward so i might give it a shot.

I just wonder why do you wish to replace clover?

**Comment by MohammadtaghiFarkhondekar** [comment]
> does this help with the first two issues or is it too old? https://github.com/MirkoCovizzi/thinkpad-p51-hackintosh#hardware
> 
> unfortunately i don't have any experience with OpenCore but the [docs](https://github.com/acidanthera/OpenCorePkg/raw/master/Docs/Configuration.pdf) look pretty neat and straightforward so i might give it a shot.
> 
> I just wonder why do you wish to replace clover?


This project is too old and It has problem with CPU .
I need User helping bc I haven't time for fixing all of problem . 
clover is old we should to use OpenCore.

**Comment by e-senturk** [comment]
I create an opencore build for that device I ll share it but I dont have that device anymore you need to check that build that might be an older version.

**Comment by MohammadtaghiFarkhondekar** [comment]
> I create an opencore build for that device I ll share it but I dont have that device anymore you need to check that build that might be an older version.

thank you . use v12 for making . after make send here for testing .

**Comment by e-senturk** [comment]
Sadly you cant be use same build in opencore and clover in order to opencore work you need to make dsdt untouched because dsdt files are enabled in both windows and mac but I fixed the issue and rewrited ssdt files I have them if you want to use same files on clover you need to update clover build as well. I ll share files need to find latest backup

**Comment by e-senturk** [comment]
There is lots of work in there. I sold my device I can't continue develop good luck. Give me a credit.
[OC.zip](https://github.com/MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD/files/4321107/OC.zip)

**Comment by keinsell** [comment]
Hello, I haven't experienced a increased power usage in rest on Catalina 10.15.3, I'm on Asus GL553VD.

**Comment by fikriardyant** [comment]
@valinor61 i use your open core build for fresh install but, it wont boot, i dont know if i do something wrong

**Comment by Nikitapls** [comment]
Thank for your work!
i install mojave and its amazing!

**Comment by ZiQiLN** [comment]
> @valinor61 i use your open core build for fresh install but, it wont boot, i dont know if i do something wrong

You can try injecting Intel and using `nv_disable=1` parameter in Clover, I had some issue when I was doing that first time but then found that solution and that worked for me.

**Comment by mhfortuna** [comment]
Hey, I have the same laptop and just wanted to say you that I could make my Intel WiFi card usable with a tutorial on YouTube: https://www.youtube.com/watch?v=ICpgYtzbxP8
Also could kinda control the RGB keyboard using this: https://github.com/hieplpvip/macrogaura
I'm on Catalina 10.15.4
If I can be of any help just contact me! I'm not a programmer tho. Thanks for your development!

**Comment by mhfortuna** [comment]
Hey! 
I just wanted to thank you for your development! Using MacOS on this device is pretty straightforward with your EFI files.
I want to share with you somethings that I've found and work!
First, a WiFi fix for the Intel card https://www.youtube.com/watch?v=ICpgYtzbxP8
It's working a bit slow, but at least I don't need an usb dongle.
The other thing I've found is a way to control the RGB of the keyboard on Catalina 10.15.4 https://github.com/hieplpvip/macrogaura
If there is anything I can do to help I'll be in touch. Thanks man!

**Comment by keinsell** [comment]
@mhfortuna I think WiFi Driver isn't ready for general usage yet, I was testing that on my 10.15.3 and doesn't work very well, okay it works but my USB Dongle with common KEXT still working better and doesn't have issues.

**Comment by keinsell** [comment]
@MohammadtaghiFarkhondekar Are you planning to migrate Clover to OpenCore? I'm asking because I just created [fork](https://github.com/ZiQiLN/macOS-GL553VD) of your repo with purpose to start slowly implementation of OpenCore Bootloader and maybe start first experiments with BigSur.

**Comment by keinsell** [comment]
I've started works with `opencore` bootloader at [my fork](https://github.com/ZiQiLN/macOS-GL553VD/), I need some testing then I'll make potential PR to this repository :D
